apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  namespace: api
spec:
  volumeName: database-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
